pragmagic/vscode-nim

syntaxes/Nim.tmLanguage

This change makes `{.pragma}` work too!

Fixes the pragma syntax

---

src/nimSignature.ts

It solves an infinte loop which somehow occurs because of a regular expression which couldn't be resolved. Also I improved how it operates with generics(where the parameter suggestion sometimes got screwed up). And at last but not least it fixes that when calling a function from a sub package of an imported package it showed the wrong selected parameter.

Fix for the signature provider

---

snippets/nim.json
src/nimMain.ts
src/nimSignature.ts

* Fixed #35 
* Readded bracket auto closing(it is intended that the string literals are brackets, VSCode recognises this and doesn't show a box around quotation marks)
* Fixed signature completion of iterators
* Fixed two snippets which pasted invalid code

Some small fixes

---

src/nimMain.ts

- These changes allow to run/compile **[F6]** a file that has a path with spaces.
- Tested under **Windows 10** and **Xubuntu 16.10**.
[nim-0.5.19.vsix.zip](https://github.com/pragmagic/vscode-nim/files/811453/nim-0.5.19.vsix.zip)

Allows compile/run files in a path with spaces

---

nimcfg.json
package.json
src/nimMain.ts

* Refixed #32 
* Added support for auto bracket closing in nimble files
* Improved the identation pattern to work on statement macros

Some small improvements

---

src/nimUtils.ts

The output of ```readlink``` without the -f flag is a non absolute path. As a result, if you used brew to install nim, the correct binary can't be detected and the error message is shown.
See https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac#4031502 on the readlink problem and a solution.
My solution is a bit hacky but should work on all OS X versions.

Fixing 'nim' binary could not be found in PATH on OS X

---

syntaxes/nim.json

`with` and `without` are not keywords anymore:
https://github.com/nim-lang/Nim/commit/3ccc9c467d84dc8c3412acbea20fc10b5335eaa8

Remove `with` and `without`

---

syntaxes/nim.json

https://github.com/nim-lang/Nim/commit/b2c358be96e496c37f4d02b0e886a06ed503af9e - `using` is not experimental anymore

Add `using` and `concept` keywords

---

README.md

Current build instructions use deprecated properties. 
Updates the instructions to what works well in recent versions of VSCode.

Updates the build task instructions

---

syntaxes/nim.json

- Don't highlight `float8` and `float16`
- Always highlight language keywords consistently
- Highlight export marker for type when followed by pragma or generic parameter
- Lots of fixes for handling extended raw string syntax
- Don't highlight `inf`
- Highlight `Inf`, `NegInf` and `NaN`

Improve syntax highlignting

---

syntaxes/nim.json

I made a mistake in #75 that caused empty raw strings to break the highlighting.

Fix syntax highlighting of empty raw string

---

syntaxes/nim.json

#99 was incorrectly closed, the syntax definition was outdated.
`\n` was changed to be an alias to `\l` a while back. `\p` does what `\n` did before.
[See manual](https://nim-lang.org/docs/manual.html#lexical-analysis-string-literals)

Update string escapes

---

syntaxes/nim.json

- Highlight the `\uHHHH` and `\u{H+}` escapes (see https://github.com/nim-lang/Nim/pull/9390)
- Highlight the `""` escape in raw strings
- Improved highlight of pragmas (see screenshoot)
- Highlight interpolated code when `strformat.fmt` is used

Syntax improvements

---

src/elrpc/elrpc.ts

Current envelope length caused a crash when directory contained Unicode characters (which weighted more than 1 byte), because nimsuggest expects size in bytes, not characters.

Fix nimsuggest on paths with Unicode characters

---

syntaxes/nim.json

Implements highlight for string block literals as discussed in nim-lang/RFCs#161
Additionally highlights any unknown string escapes. Otherwise should not affect existing code.

Block string literals

---

src/nimHover.ts

Nimsuggest returns the position where the symbol is defined, so when you hover on a symbol it gets shown at the position of the definition if it's in the same file, or in a seemingly random position if it's defined in another file.

Fix incorrect position of symbol hover info

---

README.md

Modified tasks.json file to target the current nim file and build to "bin/". I realise the build to bin is opinionated. I think including ${fileBasename} is useful though.

Update tasks.json in readme.md 

---

src/nimBuild.ts
src/nimSuggestExec.ts
src/nimUtils.ts

There are some changes to `inim` (0.5.0) which makes it possible to turn off auto-indent (`--noAutoIndent`). This makes it behave more like `ipython` when sending text to it, ie. no added spaces to lines.  It enables basic REPL-driven development where you send selected lines to the terminal for evaluation.
Specifically, this PR:
- Select terminal you want to run, `nim secret` or `inim`
- Maintain the indentation of lines sent to the terminal. For example, you have a few empty lines in the middle of a code block, these will be padded with spaces to not trigger compilation (single empty lines signal end of code block `inim` and `ipython` and will run that code, for example.
- Refactor file ending lookup of executables on Windows. It assumed only `.exe` before, now supports `.exe, .cmd or …

Support for `inim`. Maintain indentation of code blocks when sending code blocks to terminal

---

syntaxes/nim.json

this was crashing my editor implementation:
```console
$ babi test.nim
...
File "/home/asottile/workspace/babi-grammars/venv/lib/python3.6/site-packages/babi/highlight.py", line 132, in make
for k, v in dct['endCaptures'].items()
File "/home/asottile/workspace/babi-grammars/venv/lib/python3.6/site-packages/babi/highlight.py", line 132, in <genexpr>
for k, v in dct['endCaptures'].items()
File "/home/asottile/workspace/babi-grammars/venv/lib/python3.6/site-packages/babi/highlight.py", line 106, in make
name = _split_name(dct.get('name'))
AttributeError: 'str' object has no attribute 'get'
```

fix a few small mistakes in the nim textmate grammar

---

syntaxes/nim.json

The correct scope for html is `text.html.basic`
This seems to be a common issue with grammars originally imported from textmate but in vscode the correct scope is `text.html.basic`
References: https://github.com/microsoft/vscode/blob/ad407028575a77ea387eb7cc219b323dc017b686/extensions/shellscript/syntaxes/shell-unix-bash.tmLanguage.json#L454
https://github.com/microsoft/vscode/blob/ad407028575a77ea387eb7cc219b323dc017b686/extensions/handlebars/syntaxes/Handlebars.tmLanguage.json#L42
https://github.com/microsoft/vscode/blob/ad407028575a77ea387eb7cc219b323dc017b686/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json#L125
No need to change contentName since it's relative to this grammar only.

Fix html scope to text.html.basic
